// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SummerveldHoundResortAPIServer.Data;

namespace SummerveldHoundResortAPIServer.Migrations
{
    [DbContext(typeof(DoggoDataContext))]
    [Migration("20201014165853_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SummerveldHoundResortAPIServer.Models.Doggo", b =>
                {
                    b.Property<int>("DoggoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DoggoDateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DoggoDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DoggoNickname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DoggoProfilePic")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DoggoId");

                    b.ToTable("doggo");
                });
#pragma warning restore 612, 618
        }
    }
}
